use_frameworks!

platform :ios, '10.0'

target 'WESE-Example-Pods' do
  pod 'WebEngage'
end

target 'WESE-Example-SPM' do
  pod 'WebEngage'
end

target 'PODS-ServiceExtension' do
  pod 'WEServiceExtension', :path => '../'
end
